import numpy as np

word1 = 'ATAGCAGAGTCTGGGAGGCTGTCCGCTTTTCAGTTTGTCTAAAGGTTAGGGCAGTTGATGTTTGCATACTTGAAAAGTAAAGAGGTGTTTAATGATTGCAAGCTCATGTAAGTGAGTGCCTGTAACGTCCCTAATTAGGCTATGTGGTTCGCACTTTATATTATCTTCTTAAAATGAACTGTGTATTTTTTTCCTTTCTCTTTCCATATGTGTAGATATAGATACGATTTTTAAGATGCAGCCTCAAACTTCCCGTCTCCGTCTCCCATGTGCTGAGATTACAGACATGGGCTGGGTTTACTGTGGATCCAAGCTTAGAGACAAGGAAACTGAGCAAATAAAACAGTCAAGATTCCAGACAGAAAGTGGCATAGGTGGTATATAAAAGCCAAAATGTGGAGTTTTAAGTCGATCATGAGTTAACATATTAAGTGTTTGATTACTAACACAAAATGAAATTACTTGGGAACTAAACTTCCCTGTAACGACTCCTTTTCCTCTAAGTAAAACTAAGGAAGTTCTAAGAGGATGGAAAGGTTTACACAGGAAAGAACTGCTTTAGTTCCTGGTGAGAAGAAAAAGCAAACCTTAGGGTTAGGA'
word2 = 'ATAGCAGAGTCTGGGAGGCTGTCCGCTTTTCAGTTTGTCTAAAGGTTAGGGCAGTTGATGTTTGCATCTTGAAAAGTAAAGAGGTGTTTAATGATTGCAAGCTCATGTAAGTGAGTGCCTGTAACGTTAATTAGGCTATGTGGTTCGCACTTTATATTATCTTCTTAAAATGAACTGTGTATTTTCCTTTCTCTTTCCATATGTGTAGATATAGATACGATTTTTAAGATGCAGCCTCAAACTTCCCGTCTCCGTCTCCCATGTGCTGAGATTACAGACATGGGCTGGGTTTACTGTGGATCCAAGCTTAGAGACAAGGAAACTGAGCAAATAAAACAGTCAAGATTCCAGACAGAAAGTGGCATAGGTGGTATATAAAAGCCAAAATGTGGAGTTTTAAGTCGATCATGAGTTAACATATTAAGTGTAAGATTACTAACACAAAATGAAATTACTTGGGAACTAAACTTCCCTGTAACGACTCCTTTTCCTCTAAGTAAAACTAAGGAAGTTCTAAGAGGATGGAAAGGTTTACACAGGAAAGAACTGCTTTAGTTCCTGGTGAGAAGAAAAAGCAAACCTTAGGGTTAGG'

#word1 = 'abcdefghijklmnopqrstuvwxyz'
#word2 = 'abcdefghijklmnopqrstuvwxyz'

size1 = len(word1)
size2 = len(word2)

print(size1, size2)
matrix_points = np.zeros( (size1, size2) )



for i in range(size1):
    for j in range(size2):
        if word1[i] == word2[j]:
            matrix_points[i][j] = 1
        else:
            matrix_points[i][j] = 0


i = 0
j = 0
matches = 0

while i < size2:
    #print(matrix_points[i][j])
    if matrix_points[i][i]:
        matches += 1
    i += 1
print(matches)

res1 = ''
res2 = ''

i = 0
j = 0

#while i < size1 and j < size2:


print('\n\nTabela de alinhamento:')
print(matrix_points)

print('\n\nCadeias alinhadas:')
print(res1)
print(res2)
